#if canImport(AppKit)
import AppKit

/// Polls `NSPasteboard.general.changeCount` and emits new items into a `HistoryStore`.
///
/// AppKit does not expose a notification for pasteboard changes, so polling is the
/// standard approach used by every major clipboard manager on macOS.
public final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private let store: HistoryStore
    private let interval: TimeInterval
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Bundle IDs whose clipboard contents should be ignored (e.g. password managers).
    public var ignoredBundleIDs: Set<String> = []

    public init(
        store: HistoryStore,
        pasteboard: NSPasteboard = .general,
        interval: TimeInterval = 0.5
    ) {
        self.store = store
        self.pasteboard = pasteboard
        self.interval = interval
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        stop()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Honor concealed/transient types — password managers, secure fields.
        let types = pasteboard.types ?? []
        let concealedTypes: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        if types.contains(where: { concealedTypes.contains($0.rawValue) }) { return }

        let frontBundle = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let bundle = frontBundle, ignoredBundleIDs.contains(bundle) { return }

        if let item = Self.makeItem(from: pasteboard, sourceBundleID: frontBundle) {
            store.insert(item)
        }
    }

    static func makeItem(from pasteboard: NSPasteboard, sourceBundleID: String?) -> ClipboardItem? {
        // Prefer file URLs first — they're the most specific.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !urls.isEmpty
        {
            let joined = urls.map(\.path).joined(separator: "\n")
            return ClipboardItem(
                kind: .file,
                text: joined,
                payloadBase64: joined.data(using: .utf8)?.base64EncodedString(),
                sourceBundleID: sourceBundleID
            )
        }
        if let data = pasteboard.data(forType: .rtf),
           let attr = try? NSAttributedString(data: data, options: [:], documentAttributes: nil)
        {
            return ClipboardItem(
                kind: .richText,
                text: attr.string,
                payloadBase64: data.base64EncodedString(),
                sourceBundleID: sourceBundleID
            )
        }
        if let str = pasteboard.string(forType: .string), !str.isEmpty {
            return ClipboardItem(kind: .text, text: str, sourceBundleID: sourceBundleID)
        }
        if let img = NSImage(pasteboard: pasteboard),
           let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:])
        {
            return ClipboardItem(
                kind: .image,
                text: "[Image \(Int(img.size.width))×\(Int(img.size.height))]",
                payloadBase64: png.base64EncodedString(),
                sourceBundleID: sourceBundleID
            )
        }
        return nil
    }
}
#endif
